# Generated by Django 4.2.16 on 2024-11-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dojo',
        ),
    ]
