# Generated by Django 4.2.16 on 2024-11-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0012_remove_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
        migrations.DeleteModel(
            name='Dojo',
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
